spec:
  name: echoserver
  services:
    - name: backend
      dockerfile_path: Dockerfile
      github:
        branch: master
        repo: recruts/echoserver
      routes:
        - path: /api
    - name: frontend
      dockerfile_path: Dockerfile
      github:
        branch: master
        repo: recruts/frontend
      routes:
        - path: /